apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
data:
  model_name: "vgg19"
  log_level: "INFO"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xray-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
